name: E2E Testing

on:

  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
          
jobs:
  create-cluster:
    runs-on: self-hosted
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout test-infra
        uses: actions/checkout@v4
        with:
          repository: efiacor/test-infra-custom
          path: './test-infra-test'
          ref: main
      # - name: Call sandbox install
      #   run: sudo bash ${GITHUB_WORKSPACE}/test-infra-test/e2e/provision/init.sh NEPHIO_USER=ubuntu
      - name: copy file
        run: |
          mkdir ${GITHUB_WORKSPACE}/.kube
          chmod -R 755  ${GITHUB_WORKSPACE}/.kube
          sudo cp /tmp/kubeconfig ${GITHUB_WORKSPACE}/.kube/config
          chmod 644 ${GITHUB_WORKSPACE}/.kube/config
      - name: Check kubconfig
        run: ls -larth ${GITHUB_WORKSPACE}/.kube/
      - name: Check ls HOME
        run: ls -larth ${HOME}
      - name: Check HOME var
        run: echo ${HOME}
      - name: Call 001 script
        run: bash ${GITHUB_WORKSPACE}/test-infra-test/e2e/tests/free5gc/001.sh
        env:
          E2EDIR: /runner-tmp/nephio-fork/nephio-fork/test-infra-test/e2e
          LIBDIR: /runner-tmp/nephio-fork/nephio-fork/test-infra-test/e2e/lib

