name: E2E Testing

on:

  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
  
env:
  E2EDIR: ${GITHUB_WORKSPACE}/test-infra/e2e
  LIBDIR: ${GITHUB_WORKSPACE}/test-infra/e2e/lib
          
jobs:
  create-cluster:
    runs-on: self-hosted
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout test-infra
        uses: actions/checkout@v4
        with:
          repository: efiacor/test-infra-custom
          path: './test-infra'
          ref: main
      # - name: Call sandbox install
      #   run: sudo bash ${GITHUB_WORKSPACE}/test-infra/e2e/provision/init.sh NEPHIO_USER=ubuntu
      - name: Call 001 script
        run: sudo bash ${GITHUB_WORKSPACE}/test-infra/e2e/tests/free5gc/001.sh NEPHIO_USER=ubuntu

