name: E2E Testing

on:

  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: nephio-project/test-infra
          path: './test-infra'

